export const ENDPOINTS = {
  fleetRegistry: '/api/tankers',
  lookups: '/api/master/lookups',
  tankerUploadSubmit: '/api/tankers/upload',
  sidebar: '/api/sidebar',
  assignment: '/api/assignments?plateNumber={plateNumber}',
  pendingRegistrations: '/api/admin/pending-registrations',
  approvePendingRegistration: '/api/admin/pending-registrations/approve',
  rejectPendingRegistration: '/api/admin/pending-registrations/reject',
  activeUsers: '/api/admin/users',
  user: '/api/admin/users/{id}',
  login: '/authentication',
  employeeRegistration: '/api/users/register/employee',
  contractorRegistration: '/api/users/register/contractor',
  contractors: '/api/contractors',
} as const;
