export const ENDPOINTS = {
  fleetRegistry: '/tankers',
  lookups: '/master/lookups',
  tankerUploadSubmit: '/tankers/upload',
  sidebar: '/sidebar',
  assignment: '/assignments?plateNumber={plateNumber}',
  tankerUploadColumns: '/tanker-upload/columns',
  tankerUploadTemplate: '/tanker-upload/template',
  pendingRegistrations: '/nama/v1/api/users/pending',
  approveRegistration: '/nama/v1/api/users/{userId}/approve',
  rejectRegistration: '/nama/v1/api/users/{userId}/reject',
  approvePendingRegistration: '/admin/pending-registrations/approve',
  rejectPendingRegistration: '/admin/pending-registrations/reject',
  activeUsers: '/nama/v1/api/users',
  user: '/admin/users/{id}',
  clusters: '/nama/v1/api/master/clusters',
  login: '/nama/v1/authentication',
  employeeRegistration: '/nama/v1/api/users/register/employee',
  contractorRegistration: '/nama/v1/api/users/register/contractor',
  contractors: '/nama/v1/api/contractors',
} as const;
