export const ENDPOINTS = {
  pendingRegistrations: '/api/users/pending',
  approveRegistration: '/api/users/{userId}/approve',
  rejectRegistration: '/api/users/{userId}/reject',
  approvePendingRegistration: '/admin/pending-registrations/approve',
  rejectPendingRegistration: '/admin/pending-registrations/reject',
  activeUsers: '/api/users',
  clusters: '/api/master/clusters',
  fleetRegistry: '/api/tankers',
  lookups: '/api/master/lookups',
  tankerUploadSubmit: '/api/tankers/upload',
  sidebar: '/api/sidebar',
  assignment: '/api/assignments?plateNumber={plateNumber}',
  user: '/api/admin/users/{id}',
  login: '/authentication',
  employeeRegistration: '/api/users/register/employee',
  contractorRegistration: '/api/users/register/contractor',
  contractors: '/api/contractors',
} as const;
