import type { TankerUploadColumn } from '@/types';

export const TANKER_UPLOAD_COLUMNS: TankerUploadColumn[] = [
  {
    name: 'Reg No. (V5C)',
    required: true,
    description: 'Vehicle registration number from V5C document',
    example: '4024/M',
    recordKey: 'plateNumber',
  },
  {
    name: 'Owner / Driver Name',
    required: true,
    description: 'Full name of registered owner or primary driver',
    example: 'Ahmed Al-Balushi',
    recordKey: 'ownerName',
  },
  {
    name: 'Card No.',
    required: true,
    description: 'Unique tanker card identifier issued by Nama',
    example: 'C-0042',
    recordKey: 'cardNo',
  },
  {
    name: 'Contract Type',
    required: true,
    description: 'Personal / Government / Commercial',
    example: 'Commercial',
    recordKey: 'contractType',
  },
  {
    name: 'Tanker Type',
    required: true,
    description: 'Drinking Water / Sewage Water / Treated Effluent',
    example: 'Drinking Water',
    recordKey: 'tankerType',
  },
  {
    name: 'Capacity M3',
    required: true,
    description: 'Tank capacity in cubic metres',
    example: '2.9',
    recordKey: 'capacityM3',
  },
  {
    name: 'Capacity Gallons',
    required: false,
    description: 'Auto-computed from M³ if omitted (× 219.969)',
    example: '2642',
    recordKey: 'capacityGallons',
  },
  {
    name: 'Size Category',
    required: false,
    description: '0-700 / 700-1500 / 1500+ (derived if omitted)',
    example: '700-1500',
    recordKey: 'sizeCategory',
  },
  {
    name: 'Governorate',
    required: true,
    description: 'Governorate ID where the tanker primarily operates',
    example: '10',
    recordKey: 'governorate',
  },
  {
    name: 'Wilayat',
    required: false,
    description: 'Sub-district within the governorate',
    example: 'Bausher',
    recordKey: 'wilayat',
  },
  {
    name: 'Operation Region',
    required: false,
    description: 'Internal operational area code',
    example: 'Region-3',
    recordKey: 'operationRegion',
  },
  {
    name: 'TFS (Filling Station)',
    required: true,
    description: 'Tanker Filling Station code (DW tankers only)',
    example: 'TFS-07',
    recordKey: 'tfs',
  },
  {
    name: 'Contact Number',
    required: true,
    description: 'Driver or owner mobile number',
    example: '96891234567',
    recordKey: 'contactNumber',
  },
  {
    name: 'Email',
    required: true,
    description: 'Driver or owner email address',
    example: 'driver@example.com',
    recordKey: 'email',
  },
];
