export const USER_ACCESS = {
  EXECUTIVE_DASHBOARD: 'EXECUTIVE_DASHBOARD',
  OPERATIONS: 'OPERATIONS',
  FLEET_COMPLIANCE: 'FLEET_COMPLIANCE',
  INSPECTION_REVIEW: 'INSPECTION_REVIEW',
  PERMIT_RENEWAL: 'PERMIT_RENEWAL',
  REPORTS: 'REPORTS',
  FLEET_REGISTRY: 'FLEET_REGISTRY',
  LABEL_MANAGEMENT: 'LABEL_MANAGEMENT',
  INSPECTOR_ASSIGNMENT: 'INSPECTOR_ASSIGNMENT',
  TANKER_UPLOAD: 'TANKER_UPLOAD',
  CONFIG_NOTIFICATIONS: 'CONFIG_NOTIFICATIONS',
  CONFIG_PERMIT_SLA_RULES: 'CONFIG_PERMIT_SLA_RULES',
  CONFIG_USERS_ROLES: 'CONFIG_USERS_ROLES',
  CONFIG_INSPECTION_CHECKLIST: 'CONFIG_INSPECTION_CHECKLIST',
  CONFIG_CLUSTER_SETUP: 'CONFIG_CLUSTER_SETUP',
  CONFIG_FLEET_TARGETS: 'CONFIG_FLEET_TARGETS',
} as const;

export type UserAccess = (typeof USER_ACCESS)[keyof typeof USER_ACCESS];
